/*
 * Starter wardrobe for this deployment.
 *
 * Parsed from shop order-confirmation emails (REVOLVE, FWRD, The RealReal,
 * SKIMS). The app applies this ONCE, only when the closet is empty and the
 * browser has never been seeded, so edits and deletions always stick.
 *
 * These are pieces that were ORDERED. Anything returned or never worn should
 * be removed in the closet - select pieces and use Remove.
 */
(function () {
  const PT = (window.PT = window.PT || {});
  PT.SEED = {
    label: 'REVOLVE, FWRD, The RealReal and SKIMS orders',
    items: [
  {
    "name": "Halter Tie Tank Top",
    "brand": "Matteau",
    "size": "1",
    "category": "tops",
    "subtype": "Sleeveless",
    "color": "#141414",
    "colorName": "Black",
    "photoUrl": "https://is4.revolveassets.com/images/p/fw/b/MTEF-WS62_V1.jpg",
    "link": "",
    "retailer": "FWRD",
    "orderedAt": "2026-09-21",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "x Revolve Thelma Top",
    "brand": "Porsche",
    "size": "S",
    "category": "tops",
    "subtype": "",
    "color": "#141414",
    "colorName": "Black",
    "photoUrl": "https://is4.revolveassets.com/images/p/fw/b/PCHR-WS1_V1.jpg",
    "link": "",
    "retailer": "FWRD",
    "orderedAt": "2026-09-21",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "Harlow Tank Top",
    "brand": "Eterne",
    "size": "XS",
    "category": "tops",
    "subtype": "Sleeveless",
    "color": "#f2ece1",
    "colorName": "Ivory",
    "photoUrl": "https://is4.revolveassets.com/images/p/fw/b/ETEF-WS141_V1.jpg",
    "link": "",
    "retailer": "FWRD",
    "orderedAt": "2026-09-21",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "Sleeveless Bodysuit",
    "brand": "Helmut Lang",
    "size": "XS",
    "category": "tops",
    "subtype": "Sleeveless",
    "color": "#141414",
    "colorName": "Black",
    "photoUrl": "https://is4.revolveassets.com/images/p/fw/b/HLAN-WS610_V1.jpg",
    "link": "",
    "retailer": "FWRD",
    "orderedAt": "2026-09-21",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "Scoop Neck Tank Top",
    "brand": "KYE",
    "size": "1",
    "category": "tops",
    "subtype": "Sleeveless",
    "color": "#141414",
    "colorName": "Black",
    "photoUrl": "https://is4.revolveassets.com/images/p/fw/b/KYEF-WS16_V1.jpg",
    "link": "",
    "retailer": "FWRD",
    "orderedAt": "2026-09-21",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "Slim Racer Tank",
    "brand": "GRLFRND",
    "size": "XS",
    "category": "tops",
    "subtype": "Sleeveless",
    "color": "#141414",
    "colorName": "Black",
    "photoUrl": "https://is4.revolveassets.com/images/p/fw/b/GRLR-WS125_V1.jpg",
    "link": "",
    "retailer": "FWRD",
    "orderedAt": "2026-09-21",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "Era top",
    "brand": "Cult Naked",
    "size": "XS",
    "category": "tops",
    "subtype": "",
    "color": "#141414",
    "colorName": "Black",
    "photoUrl": "https://cdn.shopify.com/s/files/1/0199/8936/4790/files/cultnakedvalentine2521894hh_compact_cropped.jpg?v=1753905904",
    "link": "",
    "retailer": "Cult Naked",
    "orderedAt": "2026-09-21",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "Killa pants in Burnt",
    "brand": "Cult Naked",
    "size": "XS",
    "category": "tops",
    "subtype": "",
    "color": "#5a4433",
    "colorName": "Brown",
    "photoUrl": "https://cdn.shopify.com/s/files/1/0199/8936/4790/files/cultnaked99286_5b276ede-6623-4f14-ad2f-64560a74a35e_compact_cropped.jpg?v=1692289174",
    "link": "",
    "retailer": "Cult Naked",
    "orderedAt": "2026-09-21",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "Stella Vest",
    "brand": "BY.DYLN",
    "size": "XS",
    "category": "outerwear",
    "subtype": "Jacket",
    "color": "#141414",
    "colorName": "Black",
    "photoUrl": "https://is4.revolveassets.com/images/p4/ip2/pl2/BYDR-WS95_V1.jpg",
    "link": "",
    "retailer": "REVOLVE",
    "orderedAt": "2026-09-20",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "Fernanda Mini Dress",
    "brand": "Lovers and Friends",
    "size": "XS",
    "category": "dresses",
    "subtype": "Day dress",
    "color": "#141414",
    "colorName": "Black",
    "photoUrl": "https://is4.revolveassets.com/images/p4/ip2/pl2/LOVF-WD4855_V1.jpg",
    "link": "",
    "retailer": "REVOLVE",
    "orderedAt": "2026-09-20",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "The Tomcat Roller Sneak",
    "brand": "MOTHER",
    "size": "24",
    "category": "shoes",
    "subtype": "Trainers",
    "color": "#8d867c",
    "colorName": "On A Roll",
    "photoUrl": "https://is4.revolveassets.com/images/p4/ip2/pl2/MOTH-WJ2169_V1.jpg",
    "link": "",
    "retailer": "REVOLVE",
    "orderedAt": "2026-09-20",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "Satin Touch 20 Tights",
    "brand": "Wolford",
    "size": "S",
    "category": "accessories",
    "subtype": "Hosiery",
    "color": "#222f4d",
    "colorName": "Admiral",
    "photoUrl": "https://is4.revolveassets.com/images/p4/ip2/pl2/WFOR-WA43_V1.jpg",
    "link": "",
    "retailer": "REVOLVE",
    "orderedAt": "2026-09-20",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "Maxwell Jacket",
    "brand": "Nakedvice",
    "size": "XS",
    "category": "outerwear",
    "subtype": "Jacket",
    "color": "#141414",
    "colorName": "Black",
    "photoUrl": "https://is4.revolveassets.com/images/p4/ip2/pl2/NEDV-WO22_V1.jpg",
    "link": "",
    "retailer": "REVOLVE",
    "orderedAt": "2026-09-20",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "Penny Top",
    "brand": "BY.DYLN",
    "size": "XS",
    "category": "tops",
    "subtype": "",
    "color": "#141414",
    "colorName": "Black",
    "photoUrl": "https://is4.revolveassets.com/images/p4/ip2/pl2/BYDR-WS184_V1.jpg",
    "link": "",
    "retailer": "REVOLVE",
    "orderedAt": "2026-09-20",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "Penny Micro Skirt",
    "brand": "BY.DYLN",
    "size": "XS",
    "category": "bottoms",
    "subtype": "Skirt",
    "color": "#141414",
    "colorName": "Black",
    "photoUrl": "https://is4.revolveassets.com/images/p4/ip2/pl2/BYDR-WQ92_V1.jpg",
    "link": "",
    "retailer": "REVOLVE",
    "orderedAt": "2026-09-20",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "Fennel Skort",
    "brand": "NIA",
    "size": "XS",
    "category": "bottoms",
    "subtype": "Skirt",
    "color": "#3d3f42",
    "colorName": "Charcoal",
    "photoUrl": "https://is4.revolveassets.com/images/p4/ip2/pl2/NIAR-WF27_V1.jpg",
    "link": "",
    "retailer": "REVOLVE",
    "orderedAt": "2026-09-20",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "Morgan Skirt",
    "brand": "Nakedvice",
    "size": "XS",
    "category": "bottoms",
    "subtype": "Skirt",
    "color": "#141414",
    "colorName": "Black",
    "photoUrl": "https://is4.revolveassets.com/images/p4/ip2/pl2/NEDV-WQ20_V1.jpg",
    "link": "",
    "retailer": "REVOLVE",
    "orderedAt": "2026-09-20",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "Divinity Mini Skirt",
    "brand": "BUCI",
    "size": "XS",
    "category": "bottoms",
    "subtype": "Skirt",
    "color": "#141414",
    "colorName": "Black",
    "photoUrl": "https://is4.revolveassets.com/images/p4/ip2/pl2/BUCR-WQ49_V1.jpg",
    "link": "",
    "retailer": "REVOLVE",
    "orderedAt": "2026-09-20",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "Poise Mini Skirt",
    "brand": "LIONESS",
    "size": "XS",
    "category": "bottoms",
    "subtype": "Skirt",
    "color": "#4a4a2e",
    "colorName": "Dark Olive",
    "photoUrl": "https://is4.revolveassets.com/images/p4/ip2/pl2/LIOR-WQ110_V1.jpg",
    "link": "",
    "retailer": "REVOLVE",
    "orderedAt": "2026-09-20",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "Recycled Twill Trouser Mini Skirt",
    "brand": "Helsa",
    "size": "XS",
    "category": "bottoms",
    "subtype": "Skirt",
    "color": "#141414",
    "colorName": "Black",
    "photoUrl": "https://is4.revolveassets.com/images/p4/ip2/pl2/HLSA-WQ51_V1.jpg",
    "link": "",
    "retailer": "REVOLVE",
    "orderedAt": "2026-09-20",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "Snakeskin Top Handle Bag Medium",
    "brand": "Ferragamo",
    "size": "",
    "category": "bags",
    "subtype": "Day bag",
    "color": "#b79a6d",
    "colorName": "",
    "photoUrl": "https://product-images.therealreal.com/FRGMO46221_1_enlarged.jpg",
    "link": "",
    "retailer": "The RealReal",
    "orderedAt": "2026-09-20",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "Leather Tweed Pattern Jacket",
    "brand": "D&G",
    "size": "",
    "category": "outerwear",
    "subtype": "Jacket",
    "color": "#8d867c",
    "colorName": "",
    "photoUrl": "https://product-images.therealreal.com/DAG582882_1_enlarged.jpg",
    "link": "",
    "retailer": "The RealReal",
    "orderedAt": "2026-09-20",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "Python Shoulder Bag",
    "brand": "Eileen Kramer",
    "size": "",
    "category": "bags",
    "subtype": "Day bag",
    "color": "#b79a6d",
    "colorName": "",
    "photoUrl": "https://product-images.therealreal.com/WEKIR20363_1_enlarged.jpg",
    "link": "",
    "retailer": "The RealReal",
    "orderedAt": "2026-09-20",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "COTTON RIB TANK DRESS",
    "brand": "SKIMS",
    "size": "XS",
    "category": "dresses",
    "subtype": "Sleeveless",
    "color": "#3a3a3c",
    "colorName": "SOOT",
    "photoUrl": "https://cdn.shopify.com/s/files/1/0259/5448/4284/files/SKIMS-LOUNGEWEAR-DS-DRS-9026W-SOT-FLT_28965d6c-2424-4447-a2b0-1703dd3decc5_compact_cropped.jpg?v=1775249772",
    "link": "",
    "retailer": "SKIMS",
    "orderedAt": "2026-09-19",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "SEAMLESS SCULPT THONG BODYSUIT",
    "brand": "SKIMS",
    "size": "XS",
    "category": "tops",
    "subtype": "Sleeveless",
    "color": "#16161a",
    "colorName": "ONYX",
    "photoUrl": "https://cdn.shopify.com/s/files/1/0259/5448/4284/products/SKIMS-SHAPEWEAR-SH-BST-0200-ONX_9b794cfd-c2d1-4f6f-866b-3843d70503ba_compact_cropped.jpg?v=1742587566",
    "link": "",
    "retailer": "SKIMS",
    "orderedAt": "2026-09-19",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "NikeSKIMS RIBBED SEAMLESS MICRO SCOOP BRA",
    "brand": "SKIMS",
    "size": "XS",
    "category": "tops",
    "subtype": "Sleeveless",
    "color": "#2b2d33",
    "colorName": "OBSIDIAN",
    "photoUrl": "https://cdn.shopify.com/s/files/1/0259/5448/4284/files/NIKESKIMS-BRAS-IR5061-054-FLT_compact_cropped.jpg?v=1783986148",
    "link": "",
    "retailer": "SKIMS",
    "orderedAt": "2026-09-19",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "NikeSKIMS PERFORMANCE COTTON BLEND SHORT SLEEVE V-NECK CROP TOP",
    "brand": "SKIMS",
    "size": "XS",
    "category": "bottoms",
    "subtype": "Shorts",
    "color": "#2b2d33",
    "colorName": "OBSIDIAN",
    "photoUrl": "https://cdn.shopify.com/s/files/1/0259/5448/4284/files/SKIMS-LOUNGEWEAR-IV6646-OBS-FLT_compact_cropped.jpg?v=1789351118",
    "link": "",
    "retailer": "SKIMS",
    "orderedAt": "2026-09-19",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "NikeSKIMS STUDIO STRETCH MOCK NECK BRA TOP",
    "brand": "SKIMS",
    "size": "XS",
    "category": "tops",
    "subtype": "Sleeveless",
    "color": "#2b2d33",
    "colorName": "OBSIDIAN",
    "photoUrl": "https://cdn.shopify.com/s/files/1/0259/5448/4284/files/SKIMS-BRA-IR8684-OBS_compact_cropped.jpg?v=1778006700",
    "link": "",
    "retailer": "SKIMS",
    "orderedAt": "2026-09-19",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "COTTON JERSEY LONG SLEEVE BOATNECK TOP",
    "brand": "SKIMS",
    "size": "XS",
    "category": "tops",
    "subtype": "",
    "color": "#3a3a3c",
    "colorName": "SOOT",
    "photoUrl": "https://cdn.shopify.com/s/files/1/0259/5448/4284/files/SKIMS-LOUNGEWEAR-TP-LSL-11209W-SOT-FLT_9ad8e821-defb-4d4e-8c2b-54c20fd79928_compact_cropped.jpg?v=1787784153",
    "link": "",
    "retailer": "SKIMS",
    "orderedAt": "2026-09-19",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "SKIMS SLEEP LONG SLEEVE BUTTON UP SET",
    "brand": "SKIMS",
    "size": "XS",
    "category": "dresses",
    "subtype": "",
    "color": "#8d867c",
    "colorName": "RAISIN",
    "photoUrl": "https://cdn.shopify.com/s/files/1/0259/5448/4284/files/SKIMS-LOUNGEWEAR-ST-PNS-4086-RSN-COMPOSITE-FLT_compact_cropped.jpg?v=1788979056",
    "link": "",
    "retailer": "SKIMS",
    "orderedAt": "2026-09-19",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "EVERYDAY COTTON UNLINED DEMI BRA",
    "brand": "SKIMS",
    "size": "34",
    "category": "tops",
    "subtype": "Sleeveless",
    "color": "#8d867c",
    "colorName": "CLAY HEATHER",
    "photoUrl": "https://cdn.shopify.com/s/files/1/0259/5448/4284/files/SKIMS-BRA-BR-UNL-10812W-CLT-FLT_compact_cropped.jpg?v=1770818127",
    "link": "",
    "retailer": "SKIMS",
    "orderedAt": "2026-09-19",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "ESSENTIAL KNIT ROUNDED CROPPED CARDIGAN",
    "brand": "SKIMS",
    "size": "XS",
    "category": "outerwear",
    "subtype": "Sweater",
    "color": "#16161a",
    "colorName": "ONYX",
    "photoUrl": "https://cdn.shopify.com/s/files/1/0259/5448/4284/files/SKIMS-LOUNGEWEAR-TP-LSL-12407W-ONX-FLT_compact_cropped.jpg?v=1788377640",
    "link": "",
    "retailer": "SKIMS",
    "orderedAt": "2026-09-19",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "SOFT LOUNGE SLEEP SET",
    "brand": "SKIMS",
    "size": "S",
    "category": "dresses",
    "subtype": "",
    "color": "#16161a",
    "colorName": "ONYX",
    "photoUrl": "https://cdn.shopify.com/s/files/1/0259/5448/4284/files/SKIMS-LOUNGEWEAR-AP-SET-0600-ONX-COMPOSITE_compact_cropped.jpg?v=1773095503",
    "link": "",
    "retailer": "SKIMS",
    "orderedAt": "2026-09-19",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "NikeSKIMS RIBBED SEAMLESS MUSCLE TANK",
    "brand": "SKIMS",
    "size": "XS",
    "category": "tops",
    "subtype": "Sleeveless",
    "color": "#2b2d33",
    "colorName": "OBSIDIAN",
    "photoUrl": "https://cdn.shopify.com/s/files/1/0259/5448/4284/files/NIKESKIMS-ACTIVEWEAR-IU2219-054-FLT_compact_cropped.jpg?v=1783986338",
    "link": "",
    "retailer": "SKIMS",
    "orderedAt": "2026-09-19",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "Ira Low Rise Easy Pant",
    "brand": "EAVES",
    "size": "XS",
    "category": "bottoms",
    "subtype": "Trousers",
    "color": "#141414",
    "colorName": "Black",
    "photoUrl": "https://is4.revolveassets.com/images/p4/ip2/pl2/EAVR-WP38_V1.jpg",
    "link": "",
    "retailer": "REVOLVE",
    "orderedAt": "2026-09-18",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "Tyla Stirrup Pant",
    "brand": "superdown",
    "size": "XS",
    "category": "bottoms",
    "subtype": "Trousers",
    "color": "#141414",
    "colorName": "Black",
    "photoUrl": "https://is4.revolveassets.com/images/p4/ip2/pl2/SPDW-WP271_V1.jpg",
    "link": "",
    "retailer": "REVOLVE",
    "orderedAt": "2026-09-18",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "The Lean Straight Leg Jeans",
    "brand": "RE/DONE",
    "size": "24",
    "category": "tops",
    "subtype": "",
    "color": "#1f2a40",
    "colorName": "Midnight Drive",
    "photoUrl": "https://is4.revolveassets.com/images/p4/ip2/pl2/REDR-WJ405_V1.jpg",
    "link": "",
    "retailer": "REVOLVE",
    "orderedAt": "2026-09-18",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "Low Rise Boot Jeans",
    "brand": "AGOLDE",
    "size": "24",
    "category": "shoes",
    "subtype": "Boots",
    "color": "#8d867c",
    "colorName": "Cover",
    "photoUrl": "https://is4.revolveassets.com/images/p4/ip2/pl2/AGOL-WJ775_V1.jpg",
    "link": "",
    "retailer": "REVOLVE",
    "orderedAt": "2026-09-18",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "V-neck Racerback Tank",
    "brand": "Eterne",
    "size": "XS",
    "category": "tops",
    "subtype": "Sleeveless",
    "color": "#141414",
    "colorName": "Black",
    "photoUrl": "https://is4.revolveassets.com/images/p4/ip2/pl2/ERNE-WS88_V1.jpg",
    "link": "",
    "retailer": "REVOLVE",
    "orderedAt": "2026-09-18",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "Cropped 60s Slim Tee",
    "brand": "RE/DONE",
    "size": "XS",
    "category": "tops",
    "subtype": "Short-sleeve",
    "color": "#141414",
    "colorName": "Black",
    "photoUrl": "https://is4.revolveassets.com/images/p4/ip2/pl2/REDR-WS315_V1.jpg",
    "link": "",
    "retailer": "REVOLVE",
    "orderedAt": "2026-09-18",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "The Cropped Not So Basic Tank",
    "brand": "Sold Out NYC",
    "size": "XS",
    "category": "tops",
    "subtype": "Sleeveless",
    "color": "#141414",
    "colorName": "Black",
    "photoUrl": "https://is4.revolveassets.com/images/p4/ip2/pl2/SNYR-WS18_V1.jpg",
    "link": "",
    "retailer": "REVOLVE",
    "orderedAt": "2026-09-18",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "Sisi Silk Hooded Blouse",
    "brand": "HERSKIND",
    "size": "32",
    "category": "tops",
    "subtype": "Shirt",
    "color": "#f2ece1",
    "colorName": "Off White",
    "photoUrl": "https://is4.revolveassets.com/images/p4/ip2/pl2/HSKI-WS16_V1.jpg",
    "link": "",
    "retailer": "REVOLVE",
    "orderedAt": "2026-09-18",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "Maria Mid Rise Bootcut",
    "brand": "EB Denim",
    "size": "24",
    "category": "bottoms",
    "subtype": "Jeans",
    "color": "#141414",
    "colorName": "Black",
    "photoUrl": "https://is4.revolveassets.com/images/p4/ip2/pl2/EBDR-WP25_V1.jpg",
    "link": "",
    "retailer": "REVOLVE",
    "orderedAt": "2026-09-17",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "Teodora Western Shirt",
    "brand": "LEVI'S",
    "size": "XS",
    "category": "tops",
    "subtype": "Shirt",
    "color": "#8d867c",
    "colorName": "High Vibration Western",
    "photoUrl": "https://is4.revolveassets.com/images/p4/ip2/pl2/LEIV-WS106_V1.jpg",
    "link": "",
    "retailer": "REVOLVE",
    "orderedAt": "2026-09-17",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "Reflect Full Length Legging",
    "brand": "P.E Nation",
    "size": "S",
    "category": "bottoms",
    "subtype": "Trousers",
    "color": "#4a6c94",
    "colorName": "Marine Blue",
    "photoUrl": "https://is4.revolveassets.com/images/p4/ip2/pl2/PENR-WP203_V1.jpg",
    "link": "",
    "retailer": "REVOLVE",
    "orderedAt": "2026-09-09",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "Lumify Sports Bra",
    "brand": "P.E Nation",
    "size": "XS",
    "category": "tops",
    "subtype": "Sleeveless",
    "color": "#4a6c94",
    "colorName": "Marine Blue",
    "photoUrl": "https://is4.revolveassets.com/images/p4/ip2/pl2/PENR-WI144_V1.jpg",
    "link": "",
    "retailer": "REVOLVE",
    "orderedAt": "2026-09-09",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "x REVOLVE Avani Dress",
    "brand": "SNDYS",
    "size": "XS",
    "category": "dresses",
    "subtype": "Day dress",
    "color": "#8d867c",
    "colorName": "Pear",
    "photoUrl": "https://is4.revolveassets.com/images/p4/ip2/pl2/SDYS-WD257_V1.jpg",
    "link": "",
    "retailer": "REVOLVE",
    "orderedAt": "2026-09-09",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "Moon Shoe Og Sp Sneaker",
    "brand": "Nike",
    "size": "9",
    "category": "shoes",
    "subtype": "",
    "color": "#fdfdfb",
    "colorName": "Italy Blue & White",
    "photoUrl": "https://is4.revolveassets.com/images/p4/ip2/pl2/NIKR-WZ1372_V1.jpg",
    "link": "",
    "retailer": "REVOLVE",
    "orderedAt": "2026-09-09",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "Sott Idol Tank Top",
    "brand": "Ksubi",
    "size": "XS",
    "category": "tops",
    "subtype": "Sleeveless",
    "color": "#fdfdfb",
    "colorName": "White & Green",
    "photoUrl": "https://is4.revolveassets.com/images/p4/ip2/pl2/KSUB-WS39_V1.jpg",
    "link": "",
    "retailer": "REVOLVE",
    "orderedAt": "2026-09-09",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "Scarlett Sandal",
    "brand": "Schutz",
    "size": "9",
    "category": "shoes",
    "subtype": "Flats",
    "color": "#fdfdfb",
    "colorName": "Sugar White",
    "photoUrl": "https://is4.revolveassets.com/images/p4/ip2/pl2/SCHU-WZ1929_V1.jpg",
    "link": "",
    "retailer": "REVOLVE",
    "orderedAt": "2026-09-09",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "Scooter Heel",
    "brand": "Tony Bianco",
    "size": "9",
    "category": "shoes",
    "subtype": "Heels",
    "color": "#141414",
    "colorName": "Black Como",
    "photoUrl": "https://is4.revolveassets.com/images/p4/ip2/pl2/TONR-WZ708_V1.jpg",
    "link": "",
    "retailer": "REVOLVE",
    "orderedAt": "2026-09-09",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "Sloan Slingback Pump",
    "brand": "RAYE",
    "size": "9",
    "category": "shoes",
    "subtype": "Heels",
    "color": "#f2ece1",
    "colorName": "ivory",
    "photoUrl": "https://is4.revolveassets.com/images/p4/ip2/pl2/RAYE-WZ3003_V1.jpg",
    "link": "",
    "retailer": "REVOLVE",
    "orderedAt": "2026-09-09",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "Lou Pump",
    "brand": "Schutz",
    "size": "9",
    "category": "shoes",
    "subtype": "Heels",
    "color": "#fdfdfb",
    "colorName": "White",
    "photoUrl": "https://is4.revolveassets.com/images/p4/ip2/pl2/SCHU-WZ963_V1.jpg",
    "link": "",
    "retailer": "REVOLVE",
    "orderedAt": "2026-09-09",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "Apron Double-breasted Top",
    "brand": "MATTHEW BRUCH",
    "size": "1 (XS)",
    "category": "tops",
    "subtype": "",
    "color": "#222f4d",
    "colorName": "Navy",
    "photoUrl": "https://is4.revolveassets.com/images/p4/ip2/pl2/MBRU-WS55_V1.jpg",
    "link": "",
    "retailer": "REVOLVE",
    "orderedAt": "2026-09-09",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "for FWRD Cosima Maxi Dress",
    "brand": "Eterne",
    "size": "XS",
    "category": "dresses",
    "subtype": "Day dress",
    "color": "#f2ece1",
    "colorName": "Ivory",
    "photoUrl": "https://is4.revolveassets.com/images/p/fw/b/ETEF-WD101_V1.jpg",
    "link": "",
    "retailer": "FWRD",
    "orderedAt": "2026-09-08",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "Jacksonville Top",
    "brand": "Amanda Uprichard",
    "size": "XS",
    "category": "tops",
    "subtype": "",
    "color": "#141414",
    "colorName": "Black",
    "photoUrl": "https://is4.revolveassets.com/images/p4/ip2/pl2/AMAN-WS1172_V1.jpg",
    "link": "",
    "retailer": "REVOLVE",
    "orderedAt": "2026-09-08",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "Ryland Top",
    "brand": "Amanda Uprichard",
    "size": "XS",
    "category": "tops",
    "subtype": "",
    "color": "#141414",
    "colorName": "Black",
    "photoUrl": "https://is4.revolveassets.com/images/p4/ip2/pl2/AMAN-WS1138_V1.jpg",
    "link": "",
    "retailer": "REVOLVE",
    "orderedAt": "2026-09-08",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "Knit Long Sleeve Corset Dress",
    "brand": "fleur du mal",
    "size": "XS",
    "category": "dresses",
    "subtype": "Sleeveless",
    "color": "#141414",
    "colorName": "Black",
    "photoUrl": "https://is4.revolveassets.com/images/p4/ip2/pl2/FLER-WD90_V1.jpg",
    "link": "",
    "retailer": "REVOLVE",
    "orderedAt": "2026-09-08",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "Marine Full Length Pant",
    "brand": "Sanctuary",
    "size": "25",
    "category": "bottoms",
    "subtype": "Trousers",
    "color": "#8d867c",
    "colorName": "Luna Stripe",
    "photoUrl": "https://is4.revolveassets.com/images/p4/ip2/pl2/SANC-WP581_V1.jpg",
    "link": "",
    "retailer": "REVOLVE",
    "orderedAt": "2026-09-08",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "Marine Full Length Pant",
    "brand": "Sanctuary",
    "size": "24",
    "category": "bottoms",
    "subtype": "Trousers",
    "color": "#8d867c",
    "colorName": "Luna Stripe",
    "photoUrl": "https://is4.revolveassets.com/images/p4/ip2/pl2/SANC-WP581_V1.jpg",
    "link": "",
    "retailer": "REVOLVE",
    "orderedAt": "2026-09-08",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "Brandi Mesh Bodysuit",
    "brand": "SEROYA",
    "size": "XS",
    "category": "tops",
    "subtype": "Sleeveless",
    "color": "#141414",
    "colorName": "Black",
    "photoUrl": "https://is4.revolveassets.com/images/p4/ip2/pl2/SERR-WS154_V1.jpg",
    "link": "",
    "retailer": "REVOLVE",
    "orderedAt": "2026-09-05",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "Icon Tee",
    "brand": "LIONESS",
    "size": "XS",
    "category": "tops",
    "subtype": "Short-sleeve",
    "color": "#141414",
    "colorName": "Noir",
    "photoUrl": "https://is4.revolveassets.com/images/p4/ip2/pl2/LIOR-WS436_V1.jpg",
    "link": "",
    "retailer": "REVOLVE",
    "orderedAt": "2026-09-05",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "Cropped Denim Bomber Jacket",
    "brand": "Courtney Zheng",
    "size": "S",
    "category": "outerwear",
    "subtype": "Jeans",
    "color": "#3f4d63",
    "colorName": "Dark Vintage",
    "photoUrl": "https://is4.revolveassets.com/images/p4/ip2/pl2/CZHE-WO5_V1.jpg",
    "link": "",
    "retailer": "REVOLVE",
    "orderedAt": "2026-09-05",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "Off-The-Shoulder Mini Dress w/ Tags",
    "brand": "Retrof\u00eate",
    "size": "",
    "category": "dresses",
    "subtype": "Day dress",
    "color": "#8d867c",
    "colorName": "",
    "photoUrl": "https://product-images.therealreal.com/WRETO49205_1_enlarged.jpg",
    "link": "",
    "retailer": "The RealReal",
    "orderedAt": "2026-09-04",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "Halterneck Mini Dress",
    "brand": "Cult Gaia",
    "size": "",
    "category": "dresses",
    "subtype": "Day dress",
    "color": "#8d867c",
    "colorName": "",
    "photoUrl": "https://product-images.therealreal.com/WGAIA65473_1_enlarged.jpg",
    "link": "",
    "retailer": "The RealReal",
    "orderedAt": "2026-09-04",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "Leather Vest",
    "brand": "Gary Graham",
    "size": "",
    "category": "outerwear",
    "subtype": "Jacket",
    "color": "#8d867c",
    "colorName": "",
    "photoUrl": "https://product-images.therealreal.com/WGA22167_1_enlarged.jpg",
    "link": "",
    "retailer": "The RealReal",
    "orderedAt": "2026-09-04",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "Strapless Mini Dress",
    "brand": "Moschino Jeans",
    "size": "",
    "category": "dresses",
    "subtype": "Day dress",
    "color": "#8d867c",
    "colorName": "",
    "photoUrl": "https://product-images.therealreal.com/WMJ27840_1_enlarged.jpg",
    "link": "",
    "retailer": "The RealReal",
    "orderedAt": "2026-09-04",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "Pant Set w/ Tags",
    "brand": "Seroya",
    "size": "",
    "category": "dresses",
    "subtype": "Trousers",
    "color": "#8d867c",
    "colorName": "",
    "photoUrl": "https://product-images.therealreal.com/WSEYO20052_1_enlarged.jpg",
    "link": "",
    "retailer": "The RealReal",
    "orderedAt": "2026-09-04",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "Leather Shoulder Bag",
    "brand": "Coperni",
    "size": "",
    "category": "bags",
    "subtype": "Day bag",
    "color": "#8d867c",
    "colorName": "",
    "photoUrl": "https://product-images.therealreal.com/WCONI23978_1_enlarged.jpg",
    "link": "",
    "retailer": "The RealReal",
    "orderedAt": "2026-09-04",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "Birva Skirt",
    "brand": "Ronny Kobo",
    "size": "XS",
    "category": "bottoms",
    "subtype": "Skirt",
    "color": "#b79a6d",
    "colorName": "Snake Print Natural Multi",
    "photoUrl": "https://is4.revolveassets.com/images/p/fw/b/RONR-WQ204_V1.jpg",
    "link": "",
    "retailer": "FWRD",
    "orderedAt": "2026-08-31",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "HEAVY POINTELLE CAMI",
    "brand": "SKIMS",
    "size": "XS",
    "category": "tops",
    "subtype": "Sleeveless",
    "color": "#8d867c",
    "colorName": "MORGANITE",
    "photoUrl": "https://cdn.shopify.com/s/files/1/0259/5448/4284/files/SKIMS-LOUNGEWEAR-TP-TNK-11715W-MGI-FLT?v=1775252739_compact_cropped.jpg",
    "link": "",
    "retailer": "SKIMS",
    "orderedAt": "2026-04-29",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "HEAVY POINTELLE MINI SKORT",
    "brand": "SKIMS",
    "size": "S",
    "category": "bottoms",
    "subtype": "Skirt",
    "color": "#8d867c",
    "colorName": "MORGANITE",
    "photoUrl": "https://cdn.shopify.com/s/files/1/0259/5448/4284/files/SKIMS-LOUNGEWEAR-BT-SKT-11717W-MGI-FLT?v=1775252740_compact_cropped.jpg",
    "link": "",
    "retailer": "SKIMS",
    "orderedAt": "2026-04-29",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "NikeSKIMS MATTE 3\" FOLDOVER SHORT",
    "brand": "SKIMS",
    "size": "S",
    "category": "bottoms",
    "subtype": "Shorts",
    "color": "#2b2d33",
    "colorName": "OBSIDIAN",
    "photoUrl": "https://cdn.shopify.com/s/files/1/0259/5448/4284/files/SKIMS-ACTIVE-BO-SHO-9490W-OBD-FLT?v=1769319592_compact_cropped.jpg",
    "link": "",
    "retailer": "SKIMS",
    "orderedAt": "2026-04-29",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "NikeSKIMS MATTE WRAP LONG SLEEVE CROPPED TOP",
    "brand": "SKIMS",
    "size": "XS",
    "category": "tops",
    "subtype": "",
    "color": "#2b2d33",
    "colorName": "OBSIDIAN",
    "photoUrl": "https://cdn.shopify.com/s/files/1/0259/5448/4284/files/SKIMS-ACTIVE-LS-LSL-9692W-OBD-FLT?v=1769321030_compact_cropped.jpg",
    "link": "",
    "retailer": "SKIMS",
    "orderedAt": "2026-04-29",
    "agency": false,
    "time": "both",
    "source": "seed"
  }
]
  };
})();
