/*
 * Starter wardrobe for this deployment.
 *
 * The app normally begins empty and you import your own pieces. This file
 * pre-loads a closet so the hosted site is populated the moment it opens, on
 * any device, without importing anything first.
 *
 * It is applied ONCE, only when the closet is empty and has never been seeded,
 * so edits and deletions always stick. Remove this file (and its <script> tag
 * in index.html) to go back to starting empty.
 */
(function () {
  const PT = (window.PT = window.PT || {});
  PT.SEED = {
    label: 'REVOLVE orders, 16-20 September 2026',
    items: [
  {
    "name": "Maria Mid Rise Bootcut",
    "brand": "EB Denim",
    "size": "24",
    "category": "bottoms",
    "subtype": "Jeans",
    "color": "#141414",
    "colorName": "Black",
    "photoUrl": "https://is4.revolveassets.com/images/p4/ip2/pl2/EBDR-WP25_V1.jpg",
    "link": "https://www.revolve.com/r/DisplayProduct.jsp?code=EBDR-WP25",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "Teodora Western Shirt",
    "brand": "LEVI'S",
    "size": "XS",
    "category": "tops",
    "subtype": "Shirt",
    "color": "#7f96b5",
    "colorName": "High Vibration Western",
    "photoUrl": "https://is4.revolveassets.com/images/p4/ip2/pl2/LEIV-WS106_V1.jpg",
    "link": "https://www.revolve.com/r/DisplayProduct.jsp?code=LEIV-WS106",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "V-neck Racerback Tank",
    "brand": "Eterne",
    "size": "XS",
    "category": "tops",
    "subtype": "Sleeveless",
    "color": "#141414",
    "colorName": "Black",
    "photoUrl": "https://is4.revolveassets.com/images/p4/ip2/pl2/ERNE-WS88_V1.jpg",
    "link": "https://www.revolve.com/r/DisplayProduct.jsp?code=ERNE-WS88",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "Cropped 60s Slim Tee",
    "brand": "RE/DONE",
    "size": "XS",
    "category": "tops",
    "subtype": "Short-sleeve",
    "color": "#141414",
    "colorName": "Black",
    "photoUrl": "https://is4.revolveassets.com/images/p4/ip2/pl2/REDR-WS315_V1.jpg",
    "link": "https://www.revolve.com/r/DisplayProduct.jsp?code=REDR-WS315",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "The Cropped Not So Basic Tank",
    "brand": "Sold Out NYC",
    "size": "XS",
    "category": "tops",
    "subtype": "Sleeveless",
    "color": "#141414",
    "colorName": "Black",
    "photoUrl": "https://is4.revolveassets.com/images/p4/ip2/pl2/SNYR-WS18_V1.jpg",
    "link": "https://www.revolve.com/r/DisplayProduct.jsp?code=SNYR-WS18",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "Sisi Silk Hooded Blouse",
    "brand": "HERSKIND",
    "size": "32",
    "category": "tops",
    "subtype": "Long-sleeve",
    "color": "#f2ece1",
    "colorName": "Off White",
    "photoUrl": "https://is4.revolveassets.com/images/p4/ip2/pl2/HSKI-WS16_V1.jpg",
    "link": "https://www.revolve.com/r/DisplayProduct.jsp?code=HSKI-WS16",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "Ira Low Rise Easy Pant",
    "brand": "EAVES",
    "size": "XS",
    "category": "bottoms",
    "subtype": "Trousers",
    "color": "#141414",
    "colorName": "Black",
    "photoUrl": "https://is4.revolveassets.com/images/p4/ip2/pl2/EAVR-WP38_V1.jpg",
    "link": "https://www.revolve.com/r/DisplayProduct.jsp?code=EAVR-WP38",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "Tyla Stirrup Pant",
    "brand": "superdown",
    "size": "XS",
    "category": "bottoms",
    "subtype": "Trousers",
    "color": "#141414",
    "colorName": "Black",
    "photoUrl": "https://is4.revolveassets.com/images/p4/ip2/pl2/SPDW-WP271_V1.jpg",
    "link": "https://www.revolve.com/r/DisplayProduct.jsp?code=SPDW-WP271",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "The Lean Straight Leg Jeans",
    "brand": "RE/DONE",
    "size": "24",
    "category": "bottoms",
    "subtype": "Jeans",
    "color": "#2b3a52",
    "colorName": "Midnight Drive",
    "photoUrl": "https://is4.revolveassets.com/images/p4/ip2/pl2/REDR-WJ405_V1.jpg",
    "link": "https://www.revolve.com/r/DisplayProduct.jsp?code=REDR-WJ405",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "Low Rise Boot Jeans",
    "brand": "AGOLDE",
    "size": "24",
    "category": "bottoms",
    "subtype": "Jeans",
    "color": "#6b83a3",
    "colorName": "Cover",
    "photoUrl": "https://is4.revolveassets.com/images/p4/ip2/pl2/AGOL-WJ775_V1.jpg",
    "link": "https://www.revolve.com/r/DisplayProduct.jsp?code=AGOL-WJ775",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "Penny Top",
    "brand": "BY.DYLN",
    "size": "XS",
    "category": "tops",
    "subtype": "Sleeveless",
    "color": "#141414",
    "colorName": "Black",
    "photoUrl": "https://is4.revolveassets.com/images/p4/ip2/pl2/BYDR-WS184_V1.jpg",
    "link": "https://www.revolve.com/r/DisplayProduct.jsp?code=BYDR-WS184",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "Penny Micro Skirt",
    "brand": "BY.DYLN",
    "size": "XS",
    "category": "bottoms",
    "subtype": "Skirt",
    "color": "#141414",
    "colorName": "Black",
    "photoUrl": "https://is4.revolveassets.com/images/p4/ip2/pl2/BYDR-WQ92_V1.jpg",
    "link": "https://www.revolve.com/r/DisplayProduct.jsp?code=BYDR-WQ92",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "Fennel Skort",
    "brand": "NIA",
    "size": "XS",
    "category": "bottoms",
    "subtype": "Skirt",
    "color": "#3d3f42",
    "colorName": "Charcoal",
    "photoUrl": "https://is4.revolveassets.com/images/p4/ip2/pl2/NIAR-WF27_V1.jpg",
    "link": "https://www.revolve.com/r/DisplayProduct.jsp?code=NIAR-WF27",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "Morgan Skirt",
    "brand": "Nakedvice",
    "size": "XS",
    "category": "bottoms",
    "subtype": "Skirt",
    "color": "#141414",
    "colorName": "Black",
    "photoUrl": "https://is4.revolveassets.com/images/p4/ip2/pl2/NEDV-WQ20_V1.jpg",
    "link": "https://www.revolve.com/r/DisplayProduct.jsp?code=NEDV-WQ20",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "Divinity Mini Skirt",
    "brand": "BUCI",
    "size": "XS",
    "category": "bottoms",
    "subtype": "Skirt",
    "color": "#141414",
    "colorName": "Black",
    "photoUrl": "https://is4.revolveassets.com/images/p4/ip2/pl2/BUCR-WQ49_V1.jpg",
    "link": "https://www.revolve.com/r/DisplayProduct.jsp?code=BUCR-WQ49",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "Poise Mini Skirt",
    "brand": "LIONESS",
    "size": "XS",
    "category": "bottoms",
    "subtype": "Skirt",
    "color": "#4a4a2e",
    "colorName": "Dark Olive",
    "photoUrl": "https://is4.revolveassets.com/images/p4/ip2/pl2/LIOR-WQ110_V1.jpg",
    "link": "https://www.revolve.com/r/DisplayProduct.jsp?code=LIOR-WQ110",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "Recycled Twill Trouser Mini Skirt",
    "brand": "Helsa",
    "size": "XS",
    "category": "bottoms",
    "subtype": "Skirt",
    "color": "#141414",
    "colorName": "Black",
    "photoUrl": "https://is4.revolveassets.com/images/p4/ip2/pl2/HLSA-WQ51_V1.jpg",
    "link": "https://www.revolve.com/r/DisplayProduct.jsp?code=HLSA-WQ51",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "Stella Vest",
    "brand": "BY.DYLN",
    "size": "XS",
    "category": "tops",
    "subtype": "Sleeveless",
    "color": "#141414",
    "colorName": "Black",
    "photoUrl": "https://is4.revolveassets.com/images/p4/ip2/pl2/BYDR-WS95_V1.jpg",
    "link": "https://www.revolve.com/r/DisplayProduct.jsp?code=BYDR-WS95",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "Fernanda Mini Dress",
    "brand": "Lovers and Friends",
    "size": "XS",
    "category": "dresses",
    "subtype": "Evening dress",
    "color": "#141414",
    "colorName": "Black",
    "photoUrl": "https://is4.revolveassets.com/images/p4/ip2/pl2/LOVF-WD4855_V1.jpg",
    "link": "https://www.revolve.com/r/DisplayProduct.jsp?code=LOVF-WD4855",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "The Tomcat Roller Sneak",
    "brand": "MOTHER",
    "size": "24",
    "category": "shoes",
    "subtype": "Trainers",
    "color": "#e8e2d6",
    "colorName": "On A Roll",
    "photoUrl": "https://is4.revolveassets.com/images/p4/ip2/pl2/MOTH-WJ2169_V1.jpg",
    "link": "https://www.revolve.com/r/DisplayProduct.jsp?code=MOTH-WJ2169",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "Satin Touch 20 Tights",
    "brand": "Wolford",
    "size": "S",
    "category": "accessories",
    "subtype": "Hosiery",
    "color": "#222f4d",
    "colorName": "Admiral",
    "photoUrl": "https://is4.revolveassets.com/images/p4/ip2/pl2/WFOR-WA43_V1.jpg",
    "link": "https://www.revolve.com/r/DisplayProduct.jsp?code=WFOR-WA43",
    "agency": false,
    "time": "both",
    "source": "seed"
  },
  {
    "name": "Maxwell Jacket",
    "brand": "Nakedvice",
    "size": "XS",
    "category": "outerwear",
    "subtype": "Jacket",
    "color": "#141414",
    "colorName": "Black",
    "photoUrl": "https://is4.revolveassets.com/images/p4/ip2/pl2/NEDV-WO22_V1.jpg",
    "link": "https://www.revolve.com/r/DisplayProduct.jsp?code=NEDV-WO22",
    "agency": false,
    "time": "both",
    "source": "seed"
  }
]
  };
})();
